[package]
name = "idlegaymsies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
ggegui = "0.3.7"
egui_extras = "0.22.0"
image = { version = "0.24", features = ["jpeg", "png"] }
